version: '3'

volumes:
  pg_data_production:
  static_volume:
  media:

# Всё отличие – заменяем build на image и указываем, какой образ использовать
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: olkio/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/app/media
    depends_on:
      - db
      
  frontend:
    image: olkio/kittygram_frontend  # Качаем с DockerHub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: olkio/kittygram_gateway  # Качаем с DockerHub
    env_file: .env
    volumes:
      - static_volume:/static/
      - media:/media
    ports:
      - 9000:80